### PR TITLE
Bump Tor to 0.4.6.7

### PR DESCRIPTION
**Pull request by sethforprivacy**
This simply bumps the Tor version to 0.4.6.7, the latest recommended release of Tor.

I have tested this locally and have not observed any issues in building or running it after running `make update_tor_version` and then building the image.

If there is more involved in bumping versions, please let me know.

Thanks!

### CODE REVIEW

**Comment by cmehay** [comment]
thank you

**Comment by sethforprivacy** [comment]
@cmehay can you kick off a new Docker image build/tag? The latest in Docker Hub is v0.4.5.7 from 7mo ago.

Thanks!

**Comment by cmehay** [comment]
I need to update the build strategy for this project since Docker disabled the autobuild. Maybe with new github tools if they can be used for this.

Please, build the image on your side for now, this is quite easy with the Makefile.

**Comment by sethforprivacy** [comment]
> I need to update the build strategy for this project since Docker disabled the autobuild. Maybe with new github tools if they can be used for this.
> 
> Please, build the image on your side for now, this is quite easy with the Makefile.

Yes, I'm already building locally for now.

You can see an example of using Github Actions to push to Dockerhub here:

https://github.com/sethforprivacy/simple-monerod-docker/blob/main/.github/workflows/update-image-on-push.yml

**Comment by cmehay** [comment]
Thanks, this is yamhell 😢

**Pull request merged**
